---
environment: "release"
db:
  driver: "mysql"
  connection: "crynux_bridge:crynuxbridgepass@(mysql:3306)/crynux_bridge?parseTime=true"
  log:
    level: "info"
    output: "/app/data/logs/crynux_bridge_db.log"
    max_file_size: 100
    max_days: 30
    max_file_num: 5
log:
  level: "info"
  output: "/app/data/logs/crynux_bridge.log"
  max_file_size: 100
  max_days: 30
  max_file_num: 5
  features:
    llm_api_request_log_enabled: false
http:
  host: "0.0.0.0"
  port: "5028"
data_dir:
  inference_tasks: "/app/data/inference_tasks"
  model_images: "/app/data/images/models"
blockchain:
  account:
    address: "0x1cCcAcb47Ed79E7Dd6584693272692585B9B41ef"
    private_key_file: "/app/config/priv_key.txt"
relay:
  base_url: "https://relay.crynux.io"
task:
  default_sd_task_fee_cnx: 1.0
  default_sd_xl_task_fee_cnx: 2.0
  default_llm_task_fee_cnx: 5.0
  default_sd_finetune_task_fee_cnx: 15.0
  repeat_num: 1
  default_timeout: 6
  sd_finetune_timeout: 120
  default_task_version: "3.1.0"
  heartbeat_tasks:
    pending_tasks_limit: 10
    batch_size: 0
    max_tasks_per_hour: 0
    tasks:
      - task_version: "3.1.0"
        type: "sd"
        ratio: 1.0
        model: "crynux-network/sdxl-turbo"
        min_vram: 14
        fee_cnx: 2.0
      - task_version: "3.1.0"
        type: "llm"
        ratio: 0.5
        model: "Qwen/Qwen2.5-14B"
        min_vram: 32
        fee_cnx: 20.0
      - task_version: "3.1.0"
        type: "llm"
        ratio: 0.5
        model: "Qwen/Qwen2.5-32B"
        min_vram: 60
        fee_cnx: 40.0
      - task_version: "3.1.0"
        type: "llm"
        ratio: 1.0
        model: "Qwen/Qwen2.5-7B"
        min_vram: 24
        fee_cnx: 5.0
openrouter:
  models_file: "models.json"
task_schema:
  stable_diffusion_inference: "https://raw.githubusercontent.com/crynux-network/stable-diffusion-task/refs/tags/v3.1.0/schema/stable-diffusion-inference-task.json"
  gpt_inference: "https://raw.githubusercontent.com/crynux-network/gpt-task/refs/tags/v3.1.0/schema/gpt-inference-task.json"
  stable_diffusion_finetune_lora: "https://raw.githubusercontent.com/crynux-network/stable-diffusion-task/refs/tags/v3.1.0/schema/stable-diffusion-finetune-lora-task.json"
